name: Enhancement Request 💅
description: Suggest an improvement to content currently covered in the textbook.
title: '[Chapter number]'
labels:
  - enhancement
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: >-
        A clear and concise description of what the problem is. E.g. "The
        explanation of X is [...]"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: >-
        A clear and concise description of what you want to happen, and how it
        fits with the existing content.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: >-
        A clear and concise description of any alternative solutions you've
        considered, e.g. linking to external resources.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the request here.
